title: Stackbit DIY Theme
baseURL: /
params:
  layout_type: full-width
  style: classic
  palette: gray
  mode: light
  base_font: sans-serif
  header:
    title: DIY
    logo: images/1623269811994.png
    logo_alt: DIY logo
    has_primary_nav: true
    primary_nav_links:
      - label: Jugadores
        url: /features
        style: link
      - label: Directiva
        url: /about
        style: link
      - label: Noticias
        url: /blog
        style: link
      - label: Partidos
        url: /style-guide
        style: link
      - label: Live
        url: /style-guide
        style: link
    has_secondary_nav: true
    secondary_nav_links:
      - label: Contacto
        url: /contact
        style: link
      - label: Tienda
        url: /pricing
        style: primary
    has_anncmnt: false
    anncmnt_content: >-
      Curabitur ac tellus mattis, tempor ipsum eu, eleifend sapien. **[Learn
      More](/pricing/)**
    anncmnt_align: left
    anncmnt_is_home_only: true
    anncmnt_has_close: true
    anncmnt_id: new-features
  footer:
    logo: images/1623269811994.png
    logo_alt: DIY logo
    has_primary_nav: true
    primary_nav_title: Nosotros
    primary_nav_links:
      - label: Directiva
        url: /about
        style: link
      - label: Contacto
        url: /contacto
        style: link
    has_secondary_nav: true
    secondary_nav_title: Boletín
    secondary_nav_links:
      - label: Noticias
        url: /blog/category/news
        style: link
      - label: Comunicados
        url: /blog/category/general
        style: link
      - label: Historias
        url: /blog/category/tutorials
        style: link
    has_tertiary_nav: false
    tertiary_nav_title: Legal
    tertiary_nav_links:
      - label: Terms & Conditions
        url: /terms-conditions
        style: link
      - label: Privacy Policy
        url: /privacy-policy
        style: link
    has_social: true
    social_links:
      - label: FAcebook
        url: 'https://facebook.com/HidalgoFutbolClub'
        style: link
        has_icon: true
        icon: facebook
        icon_position: center
        new_window: true
      - label: Instagram
        url: 'https://instagram.com/hidalgo_fc_oficial'
        style: link
        has_icon: true
        icon: instagram
        icon_position: center
        new_window: true
      - label: Twitter
        url: 'https://twitter.com/HidalgoFC2'
        style: link
        has_icon: true
        icon: twitter
        icon_position: center
        new_window: true
    content: >-
      Hidalgo Fútbol Club. <br>
      Atitalaquia, Hidalgo, México.
  domain: 'https://prueba-1507a.netlify.app'
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
